---
- name: Run yolo Containers
  hosts: all
  vars:
    client_image: viper0418/client:v1.0.0
    backend_image: viper0418/backend:v1.0.0
    app_folder: /opt/yolo

  tasks:
    - name: Pull the client image
      community.docker.docker_image:
        name: "{{ client_image }}"
        source: pull

    - name: Pull the backend image
      community.docker.docker_image:
        name: "{{ backend_image }}"
        source: pull

    - name: Create a folder
      ansible.builtin.file:
        path: "{{ app_folder }}"
        state: directory

    - name: Copy docker-compose file from repo to folder
      ansible.builtin.template:
        src: ../docker-compose.yaml
        dest: "{{ app_folder }}/docker-compose.yaml"

    - name: Start containers
      shell: "docker-compose up -d"
      args:
        chdir: "{{ app_folder }}"