---
- name: Clone code from GitHub and Deploy
  hosts: all
  gather_facts: False

  vars:
    application_path: /opt/yolo2

  tasks:
    - name: Clone code from GitHub
      git:
        repo: https://github.com/Vinge1718/yolo.git
        dest: "{{ application_path }}"
        version: master

    - name: Install frontend dependencies
      become: true
      shell: |
        cd "{{ application_path }}/client"
        npm install
      args:
        chdir: "{{ application_path }}/client"

    - name: Start frontend application
      become: true
      shell: |
        cd "{{ application_path }}/client"
        npm start
      args:
        chdir: "{{ application_path }}/client"
      async: 0
      poll: 0

    - name: Install backend dependencies
      become: true
      shell: |
        cd "{{ application_path }}/backend"
        npm install
      args:
        chdir: "{{ application_path }}/backend"

    - name: Start backend application
      become: true
      shell: |
        cd "{{ application_path }}/backend"
        npm start
      args:
        chdir: "{{ application_path }}/backend"
      async: 0
      poll: 0
