services:
  frontend:
    container_name: frontend_container
    image: {{ client_image }}
    ports:
      - 5000:80
    networks:
      frontend-tier-network:
        ipv4_address: 172.128.0.3
  backend:
    container_name: backend_container
    image: {{ backend_image }}
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      DATABASE_URL: 'mongodb://group3:group3@172.127.0.1:27017'
    depends_on:
      - mongo
    networks:
      backend-tier-network:
        ipv4_address: 172.127.0.2
      frontend-tier-network:
        ipv4_address: 172.128.0.2
  mongo:
    container_name: backend_database
    image: mongo
    ports:
      - 27017:27017
    networks:
      backend-tier-network:
        ipv4_address: 172.127.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: group3
      MONGO_INITDB_ROOT_PASSWORD: group3


networks:
  frontend-tier-network:
    ipam:
      driver: default
      config:
        - subnet: 172.128.0.0/16
  backend-tier-network:
    ipam:
      driver: default
      config:
        - subnet: 172.127.0.0/16