version: '3'

services:
  frontend:
    container_name: frontend_container
    image: {{ client_image }}
    ports:
      - 3000:80
    networks:
      frontend-tier-network:
        ipv4_address: 172.128.0.3
  backend:
    container_name: backend_container
    image: {{ backend_image }}
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      MONGODB_URI: 'mongodb://backend:backend@172.127.0.1:27017'
    depends_on:
      - mongo
    networks:
      backend-tier-network:
        ipv4_address: 172.127.0.2
      frontend-tier-network:
        ipv4_address: 172.128.0.2
  mongo:
    container_name: backend_database
    image: mongo
    ports:
      - 27017:27017
    networks:
      backend-tier-network:
        ipv4_address: 172.127.0.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: backend
      MONGO_INITDB_ROOT_PASSWORD: backend


networks:
  frontend-tier-network:
    ipam:
      driver: default
      config:
        - subnet: 172.128.0.0/16
  backend-tier-network:
    ipam:
      driver: default
      config:
        - subnet: 172.127.0.0/16