version: '3'

services:
  client:
    container_name: client
    image: {{ client_image }}
    ports:
      - 3000:3000
    networks:
      frontend-tier-network:
        ipv4_address: 172.128.0.3
    depends_on:
      - backend

  backend:
    container_name: backend
    image: {{ backend_image }}
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      MONGODB_URI: 'mongodb://backend:backend@172.100.0.101:27017'
    networks:
      backend-tier-network:
        ipv4_address: 172.127.0.2
      frontend-tier-network:
        ipv4_address: 172.128.0.2
    depends_on:
      - database

  database:
    container_name: backend_database
    ports:
      - 27017:27017
    image: mongo
    networks:
      backend-tier-network:
        ipv4_address: 172.127.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: backend
      MONGO_INITDB_ROOT_PASSWORD: backend

networks:
  frontend-tier-network:
    ipam:
      driver: default
      config:
        - subnet: 172.128.0.0/16
  backend-tier-network:
    ipam:
      driver: default
      config:
        - subnet: 172.127.0.0/16