- name: Install Docker
  hosts: all
  vars:
    client_image: viper0418/client:v1.0.0
    backend_image: viper0418/backend:v1.0.0
    app_folder: /opt/yolo
  tasks:
    - name: Install necessary packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add docker repository into sources list
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/debian bullseye stable
        state: present

    - name: Update cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - docker-compose
        state: present
        update_cache: yes