---
- name: Provision and configure resources
  hosts: localhost  # Ansible runs locally

  tasks:
    - name: Initialize Terraform
      ansible.builtin.terraform:
        state: present
        command: init
        working_dir: "{{ playbook_dir }}/terraform"

    - name: Generate Terraform plan
      ansible.builtin.terraform:
        state: present
        command: plan
        working_dir: "{{ playbook_dir }}/terraform"
      register: plan_output

    - name: Display Terraform plan
      debug:
        var: plan_output.stdout_lines

    - name: Apply Terraform changes
      ansible.builtin.terraform:
        state: present
        command: apply
        working_dir: "{{ playbook_dir }}/terraform"
        auto_approve: true

- name: Wait for two minutes
  hosts: localhost  # Ansible runs locally
  gather_facts: false

  tasks:
    - name: Wait for the server to complete initializing
      pause:
        minutes: 2

- name: Configure Docker and run containers
  hosts: host_2  # Update with appropriate target hosts as highlighted in terraform
  gather_facts: false
  vars:
    client_image: viper0418/client:v1.0.0
    backend_image: viper0418/backend:v1.0.0
    app_folder: /opt/yolo

  roles:
    - docker-installation
    - docker-containers