---
- name: Provision and configure resources
  hosts: localhost  # Ansible runs locally

  tasks:
    - name: Terraform Init
      terraform:
        command: init
        working_dir: "{{ playbook_dir }}/terraform"

    - name: Terraform plan
      terraform:
        command: plan
        working_dir: "{{ playbook_dir }}/terraform"

    - name: Terraform apply
      terraform:
        command: apply
        project_path: "{{ playbook_dir }}/terraform"
        state: present

- name: Wait for two minutes
  hosts: localhost  # Ansible runs locally
  gather_facts: false

  tasks:
    - name: Wait for the server to complete initializing
      pause:
        minutes: 2

- name: Configure Docker and run containers
  hosts: host_2  # Update with appropriate target hosts as highlighted in terraform
  gather_facts: false
  vars:
    client_image: viper0418/client:v1.0.0
    backend_image: viper0418/backend:v1.0.0
    app_folder: /opt/yolo

  roles:
    - docker-installation
    - docker-containers