---
- name: Configure Docker and run containers
  hosts: all  # Update with appropriate target hosts
  gather_facts: false
  vars:
    client_image: viper0418/client:v1.0.0
    backend_image: viper0418/backend:v1.0.0
    app_folder: /opt/yolo

  roles:
    - docker-installation
    - docker-containers